---
title: "diveMove analysis"
author: "Benjamin Dupuis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preambule}
rm(list=ls())
library(diveMove);library(tidyverse);library(pander)
theme_set(theme_bw())

rdm_pengu <- read_rds("data/Adélie_data_18-19_EM/unknown_unbalanced_for_prediction.rds")
```


```{r merge tdr files}
depth_path <- paste0("data/Adélie_data_18-19_EM/corrected")
depth_files <- list.files(depth_path, pattern = ".rds")

my_global <- tibble()
for(my_file in depth_files){
  my_track <- read_rds(paste0(depth_path,"/", my_file))
  my_track$hunt <- ifelse(my_track$StatesNames == "Hunting", 1, 0) #for future proportion of hunting
  hz_track <- my_track[min(which(!is.na(my_track$correc_depth))):max(which(!is.na(my_track$correc_depth))),] %>%
    group_by(x = ceiling(row_number()/25), TagID) %>% #Go from 25Hz to 1Hz
    summarise(timestamp = min(Timestamp), prop_hunt = sum(hunt)/n(), depth = max(correc_depth, na.rm = T),
              dive = max(dive, na.rm = T))  %>% rename(tag_id = TagID)
  
  hz_track$trip_ID <- substr(my_file, 1, nchar(my_file)-4) #Add trip ID
  
  my_global <- rbind(my_global, hz_track)
}

#Quickly check if there is gaps in the dive
ggplot(hz_track, aes(x = timestamp, y = depth)) + scattermore::geom_scattermore()
which((hz_track$timestamp - lag(hz_track$timestamp) > 1))

my_tdr <- createTDR(time = hz_track$timestamp,
                    depth = hz_track$depth,
                    concurrentData = hz_track[,c(2,4,7)],
                    dtime = 1, file = paste0(depth_path,"/", my_file))
```

```{r dive parameters}
calib_tdr <- calibrateDepth(my_tdr, zoc.method = "offset", offset = 2)

plotTDR(calib_tdr, diveNo=50:55, what="phases", depth.lim=c(0, 80))
plotDiveModel(calib_tdr, diveNo=50)

tdrXSumm1 <- diveStats(calib_tdr)
```

